name: bbr
channels:
  - conda-forge
  - pytorch
  - anaconda
  - nvidia
dependencies:
  - python=3.9.12
  - pip=22.1.2
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=10.2
  - hydra-core=1.2.0
  - omegaconf=2.2.2
  - einops=0.4.1
  - tqdm=4.64.0
  - scipy=1.9.0
  - matplotlib=3.5.2
  - Pillow==9.2.0
  - pycocotools=2.0.4
  - ruff=0.0.282

  - pip:
    - git+https://github.com/openai/CLIP.git
    - opencv-python==4.6.0.66
    - sentence-transformers==2.2.2
    - timm==0.9.5
    - tensorboard==2.13.0
    - scikit-image==0.21.0
    - black==23.7.0
