name: move
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.6
  - pytorch=1.12.0
  - torchvision=0.13.0
  - scipy=1.7.3
  - scikit-image=0.19.2
  - tqdm
  - pip
  - pip:
    - pytorch-lightning==1.8.3.post0
    - timm==0.4.5
    - opencv-python==4.6.0.66
    - easydict